### ISSUE TITLE
Circle & md5

### ISSUE THREAD

**Issue by rackerroush** [rax-brazil/pub-ssh-keys#13]
1) Can we establish a a branch naming convention that circleCI will look for a test against before we merge into master?

2) The extra space between the hash and friendly name inside the md5sum file does not seem to impact the use of the md5 file for it's intended purpose.   Can the test in CircleCI be written for 1 or many whitespaces between the 2?

hash\w+friendly

**Comment by rackerroush** [comment]
So after researching it I see that 2 spaces means something with the md5sum tool, but it might still be relevant to setup the test to pass with either.  Systems besides linux use md5 not md5sum.

For reference I have compensated on my side to use md5sum.

**Comment by Linuturk** [comment]
This script targets production nodes that are all Linux, so I don't see the value of support OSX when we won't be running OSX on AWS for customers.

**Comment by Linuturk** [comment]
I'm working on adding branch detection for the script so the testing piece won't break.

**Comment by twistedgrim** [comment]
:+1:

**Comment by rackerroush** [comment]
People creating the file use things other than linux.  Not that this project will be long lived, but the chance that someone will use md5 instead of gnu's md5sum are not outlandish. 
Point in fact, I already have.

Once I put the md5 test on the server it works just as well as the one generated by md5sum.  My point it is the test is failing something that the ultimate check sees as good.

**Comment by rackerroush** [comment]
While we have seen some edge cased where the second space does not cause the test to fail on a md5sum file the second space is required.   Closing this issue.

md5sum can be installed on osx & home brew with the following:
brew install md5sha1sum
