### ISSUE TITLE
Root Privileges

### ISSUE THREAD

**Issue by Linuturk** [rax-brazil/pub-ssh-keys#3]
Check and make sure the script is running as root, as several commands depend on those permissions.

**Comment by rackerroush** [comment]
This is probably going to need to run as root.  The intention here is to give someone a single command to run.  What I had in mind was asking someone to run the following command on Ubuntu or CentOS based. 

curl https://raw.githubusercontent.com/rax-brazil/pub-ssh-keys/no-updates/rackerkeys.sh | bash

This script itself does not get installed on the server, and it only needs to run once manually.  This is just a stop gap.  I have tested the link posted above on ubuntu14.04 and a centos based server.

**Comment by Linuturk** [comment]
I feel like this is just as valid:

```
curl https://raw.githubusercontent.com/rax-brazil/pub-ssh-keys/master/rackerkeys.sh | sudo bash
```

The use case for the script being able to be run multiple times is when:
 * Accidentally run multiple times
 * Executed via configuration management
 * Run again to verify the setup
