### ISSUE TITLE
Impossible for rackerkeys.sh to work on forks with PRs

### ISSUE THREAD

**Issue by martinb3** [rax-brazil/pub-ssh-keys#55]
Rackerkeys.sh cannot support building from a fork, and I'm not sure it's possible to construct a valid URL for the raw files when the PR is from a fork. CIRCLE_PR_USERNAME and CIRCLE_PR_REPONAME are the only environment variables exposed, and it's impossible to construct a valid URL to the raw files in a fork using those.

https://raw.githubusercontent.com/rackerlabs/pub-ssh-keys/mart6985/rackerkeys.sh would work, for my PR #48, but the value 'mart6985' -- my branch name -- isn't available.

It might be easier to give us rights to push branches for these, otherwise I'm not sure any PRs will pass tests that use `curl` to fetch the raw files.

**Comment by martinb3** [comment]
This is likely the blocker/reason for failure on #48, #49, #52, #53, #54.

**Comment by Linuturk** [comment]
Yeah, this is a known issue and there isn't an easy solution. We are waiting for the official solution to be in place for Racker access to customer accounts and this is a temporary stop-gap measure.

**Comment by horacio3** [comment]
This looks to have been solved?!?

https://github.com/rax-brazil/pub-ssh-keys/pull/83
https://github.com/rax-brazil/pub-ssh-keys/pull/82
https://github.com/rax-brazil/pub-ssh-keys/pull/81

**Comment by martinb3** [comment]
Looks like someone fixed it in https://github.com/rax-brazil/pub-ssh-keys/commit/3b7c94a0c33004553616487e5f2bf59b20e71d66.
